# Generated by Django 2.2.4 on 2019-09-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('detailDesc', models.CharField(max_length=300)),
                ('answerCount', models.IntegerField(null=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ansContent', models.CharField(max_length=300, null=True)),
                ('ansDate', models.DateTimeField(auto_now=True, null=True)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Questions')),
            ],
        ),
    ]
